#pragma libcall AmiPiBorgBase APB_CreateContext 1e 09803
#pragma libcall AmiPiBorgBase APB_FreeContext 24 801
#pragma libcall AmiPiBorgBase APB_AllocConnection 2a 09803
#pragma libcall AmiPiBorgBase APB_FreeConnection 30 801
#pragma libcall AmiPiBorgBase APB_OpenConnection 36 801
#pragma libcall AmiPiBorgBase APB_CloseConnection 3c 801
#pragma libcall AmiPiBorgBase APB_ConnectionState 42 801
#pragma libcall AmiPiBorgBase APB_AllocRequest 48 801
#pragma libcall AmiPiBorgBase APB_FreeRequest 4e 801
#pragma libcall AmiPiBorgBase APB_Read 54 801
#pragma libcall AmiPiBorgBase APB_Write 5a 801
#pragma libcall AmiPiBorgBase APB_Abort 60 801
#pragma libcall AmiPiBorgBase APB_SrvQuit 66 0
#pragma libcall AmiPiBorgBase APB_SrvSetLogLevel 6c 001
#pragma libcall AmiPiBorgBase APB_AllocMem 72 0802
#pragma libcall AmiPiBorgBase APB_FreeMem 78 09803
#pragma libcall AmiPiBorgBase APB_RegisterStat 7e 0802
#pragma libcall AmiPiBorgBase APB_IncrementStat 84 10803
#pragma libcall AmiPiBorgBase APB_GetStat 8a 0802
#pragma libcall AmiPiBorgBase APB_SetLogLevel 90 0802
#pragma libcall AmiPiBorgBase APB_LogArgArray 96 2D1A09807
#pragma libcall AmiPiBorgBase APB_ShouldLog 9c 0802
#pragma libcall AmiPiBorgBase APB_TypeRegistered a2 0802
#pragma libcall AmiPiBorgBase APB_RegisterObjectType a8 32190806
#pragma libcall AmiPiBorgBase APB_AllocObject ae 0802
#pragma libcall AmiPiBorgBase APB_FreeObject b4 90803
